//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Destiny.Core.Flow
{
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MNZ.CMS.Core.Identity.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 乐观并发失败，对象已被修改。 的本地化字符串。
        /// </summary>
        internal static string ConcurrencyFailure {
            get {
                return ResourceManager.GetString("ConcurrencyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unknown failure has occurred. 的本地化字符串。
        /// </summary>
        internal static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email &apos;{0}&apos; is already taken. 的本地化字符串。
        /// </summary>
        internal static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role name &apos;{0}&apos; is already taken. 的本地化字符串。
        /// </summary>
        internal static string DuplicateRoleName {
            get {
                return ResourceManager.GetString("DuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name &apos;{0}&apos; is already taken. 的本地化字符串。
        /// </summary>
        internal static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email &apos;{0}&apos; is invalid. 的本地化字符串。
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type {0} must derive from {1}&lt;{2}&gt;. 的本地化字符串。
        /// </summary>
        internal static string InvalidManagerType {
            get {
                return ResourceManager.GetString("InvalidManagerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provided PasswordHasherCompatibilityMode is invalid. 的本地化字符串。
        /// </summary>
        internal static string InvalidPasswordHasherCompatibilityMode {
            get {
                return ResourceManager.GetString("InvalidPasswordHasherCompatibilityMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The iteration count must be a positive integer. 的本地化字符串。
        /// </summary>
        internal static string InvalidPasswordHasherIterationCount {
            get {
                return ResourceManager.GetString("InvalidPasswordHasherIterationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role name &apos;{0}&apos; is invalid. 的本地化字符串。
        /// </summary>
        internal static string InvalidRoleName {
            get {
                return ResourceManager.GetString("InvalidRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid token. 的本地化字符串。
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name &apos;{0}&apos; is invalid, can only contain letters or digits. 的本地化字符串。
        /// </summary>
        internal static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A user with this login already exists. 的本地化字符串。
        /// </summary>
        internal static string LoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("LoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddIdentity must be called on the service collection. 的本地化字符串。
        /// </summary>
        internal static string MustCallAddIdentity {
            get {
                return ResourceManager.GetString("MustCallAddIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No IPersonalDataProtector service was registered, this is required when ProtectPersonalData = true. 的本地化字符串。
        /// </summary>
        internal static string NoPersonalDataProtector {
            get {
                return ResourceManager.GetString("NoPersonalDataProtector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No RoleType was specified, try AddRoles&lt;TRole&gt;(). 的本地化字符串。
        /// </summary>
        internal static string NoRoleType {
            get {
                return ResourceManager.GetString("NoRoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No IUserTwoFactorTokenProvider&lt;{0}&gt; named &apos;{1}&apos; is registered. 的本地化字符串。
        /// </summary>
        internal static string NoTokenProvider {
            get {
                return ResourceManager.GetString("NoTokenProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User security stamp cannot be null. 的本地化字符串。
        /// </summary>
        internal static string NullSecurityStamp {
            get {
                return ResourceManager.GetString("NullSecurityStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incorrect password. 的本地化字符串。
        /// </summary>
        internal static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passwords must have at least one digit (&apos;0&apos;-&apos;9&apos;). 的本地化字符串。
        /// </summary>
        internal static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passwords must have at least one lowercase (&apos;a&apos;-&apos;z&apos;). 的本地化字符串。
        /// </summary>
        internal static string PasswordRequiresLower {
            get {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passwords must have at least one non alphanumeric character. 的本地化字符串。
        /// </summary>
        internal static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passwords must use at least {0} different characters. 的本地化字符串。
        /// </summary>
        internal static string PasswordRequiresUniqueChars {
            get {
                return ResourceManager.GetString("PasswordRequiresUniqueChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passwords must have at least one uppercase (&apos;A&apos;-&apos;Z&apos;). 的本地化字符串。
        /// </summary>
        internal static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passwords must be at least {0} characters. 的本地化字符串。
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recovery code redemption failed. 的本地化字符串。
        /// </summary>
        internal static string RecoveryCodeRedemptionFailed {
            get {
                return ResourceManager.GetString("RecoveryCodeRedemptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role {0} does not exist. 的本地化字符串。
        /// </summary>
        internal static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IProtectedUserStore&lt;TUser&gt; which is required when ProtectPersonalData = true. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIProtectedUserStore {
            get {
                return ResourceManager.GetString("StoreNotIProtectedUserStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IQueryableRoleStore&lt;TRole&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIQueryableRoleStore {
            get {
                return ResourceManager.GetString("StoreNotIQueryableRoleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IQueryableUserStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIQueryableUserStore {
            get {
                return ResourceManager.GetString("StoreNotIQueryableUserStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IRoleClaimStore&lt;TRole&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIRoleClaimStore {
            get {
                return ResourceManager.GetString("StoreNotIRoleClaimStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserAuthenticationTokenStore&lt;User&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserAuthenticationTokenStore {
            get {
                return ResourceManager.GetString("StoreNotIUserAuthenticationTokenStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserAuthenticatorKeyStore&lt;User&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserAuthenticatorKeyStore {
            get {
                return ResourceManager.GetString("StoreNotIUserAuthenticatorKeyStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserClaimStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserClaimStore {
            get {
                return ResourceManager.GetString("StoreNotIUserClaimStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserConfirmationStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserConfirmationStore {
            get {
                return ResourceManager.GetString("StoreNotIUserConfirmationStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserEmailStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserEmailStore {
            get {
                return ResourceManager.GetString("StoreNotIUserEmailStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserLockoutStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserLockoutStore {
            get {
                return ResourceManager.GetString("StoreNotIUserLockoutStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserLoginStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserLoginStore {
            get {
                return ResourceManager.GetString("StoreNotIUserLoginStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserPasswordStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserPasswordStore {
            get {
                return ResourceManager.GetString("StoreNotIUserPasswordStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserPhoneNumberStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserPhoneNumberStore {
            get {
                return ResourceManager.GetString("StoreNotIUserPhoneNumberStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserRoleStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserRoleStore {
            get {
                return ResourceManager.GetString("StoreNotIUserRoleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserSecurityStampStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserSecurityStampStore {
            get {
                return ResourceManager.GetString("StoreNotIUserSecurityStampStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserTwoFactorRecoveryCodeStore&lt;User&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserTwoFactorRecoveryCodeStore {
            get {
                return ResourceManager.GetString("StoreNotIUserTwoFactorRecoveryCodeStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store does not implement IUserTwoFactorStore&lt;TUser&gt;. 的本地化字符串。
        /// </summary>
        internal static string StoreNotIUserTwoFactorStore {
            get {
                return ResourceManager.GetString("StoreNotIUserTwoFactorStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User already has a password set. 的本地化字符串。
        /// </summary>
        internal static string UserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("UserAlreadyHasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User already in role &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string UserAlreadyInRole {
            get {
                return ResourceManager.GetString("UserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User is locked out. 的本地化字符串。
        /// </summary>
        internal static string UserLockedOut {
            get {
                return ResourceManager.GetString("UserLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lockout is not enabled for this user. 的本地化字符串。
        /// </summary>
        internal static string UserLockoutNotEnabled {
            get {
                return ResourceManager.GetString("UserLockoutNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User {0} does not exist. 的本地化字符串。
        /// </summary>
        internal static string UserNameNotFound {
            get {
                return ResourceManager.GetString("UserNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User is not in role &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string UserNotInRole {
            get {
                return ResourceManager.GetString("UserNotInRole", resourceCulture);
            }
        }
    }
}
